config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: [:new, :create, :show, :index, :destroy]

  get '/my-projects', to: 'projects#my_projects', as: 'my_projects'
  resources :skills, only: [:new, :create, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'matches#index'
  resources :users, only: [:show]

  # routes for liking and disliking a user
  post '/like-user/:liked_user', to: 'matches#liked', as: 'like_user'
  post '/dislike-user/:disliked_user', to: 'matches#disliked', as: 'dislike_user'

  # user matches page
  get '/matches', to: 'users#matches', as: 'matches'

  # handle photo upload
  put 'photo-upload', to: 'users#photo_upload', as: 'photo_upload'

  # route for showing chats
  get '/chats/:id', to: 'chats#show', as: 'chat'

  # creating a new chat
  post '/chats/:match_id', to: 'chats#create', as: 'new_chat'

  # adding a collaborator to a project
  post '/add-collaborator', to: 'projects#add_collaborator', as: 'add_collaborator'
  # setting featured project
  post '/featured-project/:project_id',  to: 'projects#set_featured_project', as: 'featured_project'

  resources :messages
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one_attached :avatar
  has_many :matches
  # all the users that I have liked
  has_many :liked_users, through: :matches

  # all the people who have liked me
  has_many :likers, foreign_key: :liked_user_id, class_name: 'Match'
  has_many :liker_users, through: :likers, source: :user

  has_many :projects

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def filter_users
    # returns a filtered list of users that no longer need to show for
    # the current logged in user on the match page
    User.all.select do |user|
      matches_self_created = Match.all.find_by(user: self, liked_user: user)
      matches_user_created = Match.all.find_by(user: user, liked_user: self, is_denied: true)
      self_matches = Match.all.find_by(user: self, liked_user: user, is_matched: true)
      user_matches = Match.all.find_by(user: user, liked_user: self, is_matched: true)

      case user
      when self
        # filter out self
        false
      when matches_self_created.nil? ? self : matches_self_created.liked_user
        # filter out users that you have already liked
        # filter out users that you denied
        false
      when matches_user_created.nil? ? self : matches_user_created.user
        # filter out users that denied you
        false
      when self_matches.nil? ? self : self_matches.liked_user
        false
      when user_matches.nil? ? self : user_matches.user
        false
      else
        true
      end
    end
  end

  def my_matches
    # This function returns all the matches where the user is involved
    # both matches that the user created and matches where this user was liked or denied
    (matches + Match.all.where(liked_user: self)).select do |match|
      match.is_matched == true && match.is_denied == false
    end
  end

  def my_matches_users
    # maps over array of all matches and returns the users
    my_matches.map do |match|
      match.user == self ? match.liked_user : match.user
    end
  end

  def find_match(user)
    Match.find_by(user: self, liked_user: user).nil? ? Match.find_by(user: user, liked_user: self) : Match.find_by(user: self, liked_user: user)
  end

  def featured_project(featured_project)
    selected_project = Project.find(featured_project)
    self.projects.each do |project|
        project.update(is_featured: false) 
    end
    selected_project.update(is_featured: true)
end
  
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end


  def matches
    @user = current_user
  end

  def photo_upload
    current_user.avatar.attach(params[:avatar])
    redirect_to user_path(current_user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_match_card.html.erb
<div class="match-card">
   <%= render partial: 'users/user_pic', locals: {user: user}  %>
  <h3><%=user.first_name %></h3>
  <p><%=user.city %></p>
  <%= link_to (fa_icon 'envelope 3x' ), new_chat_path(match), method: :post %>

     <%= button_to "Unmatch", dislike_user_path(user), method: :post, class: 'btn btn-danger' %>
</div>

app/views/users/_user_pic.html.erb
<% if user.avatar.attached? %>
    <%= image_tag user.avatar %>
  <% else %>
    <%= image_tag "default-pic.png" %>
  <% end %>

app/views/users/matches.html.erb
<h1>Your Matches</h1>
<p>You have <%=@user.my_matches.size %> matches! Damn you're popular 🔥🔥🔥</p>
<div class="match-grid">
  <% @user.my_matches_users.each do |user| %>
    <%= render partial: "match_card", locals: {user: user, match: current_user.find_match(user)} %>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
    <div class= "profile-page-img">
      <%= render partial: 'users/user_pic', locals: {user: @user}  %>
    </div>
    <h3><%=@user.first_name %></h3>
    <p><%=@user.city %></p>
    <p><%=@user.occupation %></p>
    <p><%= link_to "Edit Profile", edit_user_registration_path %></p>
</div>


<% if @user.projects %>
  <div class="project-grid">
    <% @user.projects.each do |project| %>
      <%= render partial: "projects/project_card", locals: {project: project} %>
    <% end %>
  </div>
<% end %>