config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: [:new, :create, :show, :index, :destroy]

  get '/my-projects', to: 'projects#my_projects', as: 'my_projects'
  resources :skills, only: [:new, :create, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'matches#index'
  resources :users, only: [:show]

  # routes for liking and disliking a user
  post '/like-user/:liked_user', to: 'matches#liked', as: 'like_user'
  post '/dislike-user/:disliked_user', to: 'matches#disliked', as: 'dislike_user'

  # user matches page
  get '/matches', to: 'users#matches', as: 'matches'

  # handle photo upload
  put 'photo-upload', to: 'users#photo_upload', as: 'photo_upload'

  # route for showing chats
  get '/chats/:id', to: 'chats#show', as: 'chat'

  # creating a new chat
  post '/chats/:match_id', to: 'chats#create', as: 'new_chat'

  # adding a collaborator to a project
  post '/add-collaborator', to: 'projects#add_collaborator', as: 'add_collaborator'
  # setting featured project
  post '/featured-project/:project_id',  to: 'projects#set_featured_project', as: 'featured_project'

  resources :messages
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :project_skills
    has_many :skills, through: :project_skills
    has_many :collaborators
    accepts_nested_attributes_for :project_skills

   


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!

    def index
        @projects = Project.all
    end

    def new
        @project = Project.new
        @user = current_user
    end

    def destroy
        @project = Project.find(params[:id]) 
        @project.destroy
        flash[:notice] = "Project has been deleted." 
        redirect_to user_path(current_user)
    end

    

    def show
        @project = Project.find(params[:id])
        
    end

    def create
        @project = Project.create(project_params)
        redirect_to project_path(@project)
    end

    def set_featured_project
        current_user.featured_project(params[:project_id])
        redirect_to my_projects_path
    end

    def add_collaborator
        Collaborator.find_or_create_by(project_id: params[:project_id], user_id: params[:user][:id])
        redirect_to project_path(params[:project_id])
    end

    private
    def project_params
        params.require(:project).permit(:user_id, :name, :description, skill_ids:[])
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_collaborator.html.erb
<%= form_tag '/add-collaborator', method: :post do %>
  <%= hidden_field_tag :project_id, project.id %>
  <%= collection_select :user, :id, current_user.my_matches_users, :id, :first_name %>
  <button type="submit">Add Collaborator</button>
<% end %>

app/views/projects/_collaborator_card.html.erb
<div class="collaborator">
  <%= render partial: 'users/user_pic', locals: {user: user}  %>
  <h4><%= user.first_name %></h4>
</div>

app/views/projects/_project_card.html.erb
<div class="project-card">
  <h4><%= link_to project.name, project_path(project) %></h4>
  <p><%= project.description %></p>
  <div class="project-card-skills ">
    <% project.skills.each do |skill| %>
      <p class="skill-card"><%= skill.name %></p>
    <% end %>
  </div>
  <div class="project-actions">
    <% if project.is_featured %>
      <p class="star"> <%= fa_icon 'star' %>Featured Project</p>
    <% else %>
      <%= link_to "Set as featured project", featured_project_path(project), method: :post %>
    <% end %>
    <%= link_to 'Delete this project', project_path(project), method: :delete, data: {confirm: 'Are you sure you would like to delete this project?'} %>
  </div>
</div>

app/views/projects/index.html.erb
<h1>My Projects</h1>
<% @projects.each do |project| %>
    <%= project.name %>
<% end %>

app/views/projects/my_projects.html.erb
<div class="project-grid">
  <% current_user.projects.each do |project| %>
    <%= render partial: 'project_card', locals: {project: project} %>
  <% end %>
</div>

<hr>

 <%= link_to "Add a new project", new_project_path %>

app/views/projects/new.html.erb
<div class="container ">
    <div class="col-md-4 mx-auto text-center">
        </div>
            <div class="row">
                <div class="header-title">
                    <h1 class="wv-heading--title">
                    Create a new project
                    </h1>
                    <h6 class="wv-heading--subtitle">
                        Add a new project to your profile to start matching with potential collaborators
                    </h6>
                </div>
            </div>
            <div class="myform form">
                <%= form_for @project do |f| %>
                <div class='form-group'>
                    <%= f.text_field :name, class: "form-control my-input", placeholder: 'Project Name' %>
                </div>
                <div class='form-group'>
                    <%= f.text_area :description, class: "form-control my-input", placeholder: 'Tell us more about your your project'%>
                </div>
                <div class='form-group'>
                    <%= f.hidden_field :user_id, :value => @user.id %>
                </div>
                <div class='form-group checkbox-list'>
                    <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name, {:item_wrapper_class => 'checkbox_container'} %>
                </div>
                <div class='form-group'>
                        <%= f.submit %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class=project-show-wrapper>
  <h2><%= @project.name %></h2>
  <p><%= @project.description %></p>
  <div class="skill-card-grid">
    <% @project.skills.each do |skill| %>
      <div class=skill-card><%= skill.name %></div>  
    <% end %>
  </div>
  <% if !@project.collaborators.empty? %>
    <div class="collaborator-grid">
      <% @project.collaborators.each do |collaborator| %>
        <%= render partial: 'collaborator_card', locals: {user: collaborator.user} %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="margin-top">
  <% if @project.user == current_user %>
    <%= render partial: 'add_collaborator', locals: {project: @project} %>
  <% end %>
</div>