config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: [:new, :create, :show, :index, :destroy]

  get '/my-projects', to: 'projects#my_projects', as: 'my_projects'
  resources :skills, only: [:new, :create, :show]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'matches#index'
  resources :users, only: [:show]

  # routes for liking and disliking a user
  post '/like-user/:liked_user', to: 'matches#liked', as: 'like_user'
  post '/dislike-user/:disliked_user', to: 'matches#disliked', as: 'dislike_user'

  # user matches page
  get '/matches', to: 'users#matches', as: 'matches'

  # handle photo upload
  put 'photo-upload', to: 'users#photo_upload', as: 'photo_upload'

  # route for showing chats
  get '/chats/:id', to: 'chats#show', as: 'chat'

  # creating a new chat
  post '/chats/:match_id', to: 'chats#create', as: 'new_chat'

  # adding a collaborator to a project
  post '/add-collaborator', to: 'projects#add_collaborator', as: 'add_collaborator'
  # setting featured project
  post '/featured-project/:project_id',  to: 'projects#set_featured_project', as: 'featured_project'

  resources :messages
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  belongs_to :user
  belongs_to :liked_user, class_name: 'User'
  has_one :chat
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = current_user.filter_users
  end

  def liked
    @liked_user = User.find(params[:liked_user])
    @user = current_user
    if Match.all.find_by(user: @liked_user, liked_user: @user)
      match = Match.all.find_by(user: @liked_user, liked_user: @user)
      match.update(is_matched: true)
    else
      Match.create(user_id: @user.id, liked_user_id: @liked_user.id)
    end
    redirect_to root_path
  end

  def disliked
    @disliked_user = User.find(params[:disliked_user])
    @user = current_user
    if Match.all.find_by(user: @disliked_user, liked_user: @user)
      match = Match.all.find_by(user: @disliked_user, liked_user: @user)
      match.update(is_denied: true)
    else
      Match.create(user_id: @user.id, liked_user_id: @disliked_user.id, is_denied: true)
    end
    redirect_to root_path
  end
end

app/helpers/matches_helper.rb
# frozen_string_literal: true

module MatchesHelper
end

app/views/matches/_user_card.html.erb
<div class="user-card">
  <%= render partial: 'users/user_pic', locals: {user: user}  %>
  <div class="content">
    <h2><%=user.first_name %></h2>
    <p><%=user.city %></p>
    <p><%=user.occupation %></p>
    <% project = user.projects.find_by(is_featured: true) %>
    <% if project %>
      <i><p>Currently working on:</p></i> 
      <%= fa_icon 'laptop' %>
      <%= link_to project.name , project_path(project) %>
    <% end %>
    <p> <% %></p>
    <div class="buttons">
      <%= link_to (fa_icon 'check-circle 3x'), like_user_path(user), method: :post, class: 'checkmark' %>
      <%= link_to (fa_icon 'times-circle 3x'), dislike_user_path(user), method: :post, class: 'cross' %>
    </div>
  </div>
</div>

app/views/matches/index.html.erb
<%# Show all the users that the current user has liked %>
<%# Problem with when a user denies someone they still show up %>
<%# because user.liked_uses doesnt take into account the booleans %>

<% if @users.nil? %>
  <p>Youve liked everyone</p>
<% else %>
  <div class="cards-grid">
    <% @users.each do |user| %>
      <%= render partial: "user_card", locals: {user: user} %>
    <% end %>
  </div>
<% end %>